# Generated by Django 3.0.3 on 2020-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pizzeria')),
                ('description', models.TextField(verbose_name='Description')),
                ('raiting', models.FloatField(default=0, verbose_name='Raiting')),
                ('url', models.URLField(verbose_name='Internet address')),
            ],
        ),
    ]
