# Generated by Django 3.0.3 on 2020-02-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizzeria', 'verbose_name_plural': 'Pizzerias'},
        ),
        migrations.AlterModelOptions(
            name='pizzashop',
            options={'verbose_name': 'Pizzeria', 'verbose_name_plural': 'Pizzerias'},
        ),
    ]
