# Generated by Django 3.0.3 on 2020-02-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200213_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizzeria', 'verbose_name_plural': 'Pizzas'},
        ),
    ]
